version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 896924684590.dkr.ecr.ap-south-1.amazonaws.com)
      - REPOSITORY_URI=896924684590.dkr.ecr.ap-south-1.amazonaws.com/janani-repo
      - IMAGE_TAG=new-image1
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region ap-south-1 --name cluster1

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Deploying to EKS...
      - kubectl apply -f deployment.yaml
      - echo Deployment complete.

artifacts:
  files:
    - deployment.yaml