apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-task-deployment
  labels:
    app: brain-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brain-task
  template:
    metadata:
      labels:
        app: brain-task
    spec:
      containers:
        - name: brain-task-container
          image: 896924684590.dkr.ecr.ap-south-1.amazonaws.com/janani-repo:latest
          ports:
            - containerPort: 3000