apiVersion: apps/v1
kind: Deployment
metadata:
  name: janani-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: janani-app
  template:
    metadata:
      labels:
        app: janani-app
    spec:
      containers:
        - name: janani-container
          image: 896924684590.dkr.ecr.ap-south-1.amazonaws.com/janani-repo:new-image1
          ports:
            - containerPort: 80