apiVersion: v1
kind: Service
apiVersion: v1
kind: Service
metadata:
  name: janani-service
spec:
  selector:
    app: janani-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer