apiVersion: v1
kind: Service
apiVersion: v1
kind: Service
apiVersion: v1
kind: Service
metadata:
  name: brain-task-service
spec:
  type: LoadBalancer
  selector:
    app: brain-task
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000